### ISSUE TITLE
Error Executing

### ISSUE THREAD

**Issue by rpb-dev** [mame82/duck2spark#2] opened 2017-02-12 19:04 UTC
C:\Users\Lambda\Downloads\duck2spark-master\duck2spark-master>duck2spark.py -i raw.bin -l 1 -f 2000
Traceback (most recent call last):
  File "C:\Users\Lambda\Downloads\duck2spark-master\duck2spark-master\duck2spark.py", line 154, in <module>
    main(sys.argv[1:])
  File "C:\Users\Lambda\Downloads\duck2spark-master\duck2spark-master\duck2spark.py", line 122, in main
    with open(ifile,"read") as f:
ValueError: Invalid mode ('read')

C:\Users\Lambda\Downloads\duck2spark-master\duck2spark-master>

**Comment by mame82** [comment] 2017-02-12 20:21
There has been an issue in the file opening mode. Please try the updated master branch.
If the error remains please give Details on your python Version and OS.

**Comment by mame82** [comment] 2017-02-14 20:06
@rpborges97  does it work for you? Going to close this issue by the end of the week. I'm not able to reproduce  it anymore.

**Comment by mame82** [comment] 2017-02-18 18:33
No feedback

**Closed as completed** 2017-02-18 18:33 UTC
Labels: help wanted
